# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values
#do not exceed four million, find the sum of the even-valued terms. 


first_prev_num = 2
sec_prev_num = 1
total = 2
new_num = 0

while new_num < 4000000:
    new_num = first_prev_num + sec_prev_num
    sec_prev_num = first_prev_num
    first_prev_num = new_num
    if (new_num % 2 == 0):
      total = total + new_num
print("The total is ", total)
